name: Shobit Maven CI/CD #na

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: docker build -t img:${{github.sha}}.
      - name: Publish Docker image
        run: docker push img:${{github.sha}}

